spring.application.name=scraper

spring.datasource.url=jdbc:postgresql://localhost:5432/scraper
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql

storage.path=./compressed-images

threads.pool=10